# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

#services:
  #ollama-server:
    #image: ollama/ollama
    #container_name: ollama-server
    #ports:
      #- ${LLM_ENDPOINT_PORT:-8008}:11434
    #environment:
     # no_proxy: ${no_proxy}
      #http_proxy: ${http_proxy}
      #https_proxy: ${https_proxy}
     #LLM_MODEL_ID: ${LLM_MODEL_ID}
      #host_ip: ${host_ip}

networks:
  default:
    driver: bridge

    services:
  speecht5-service:
    image: ${REGISTRY:-opea}/speecht5:${TAG:-latest}
    container_name: speecht5-service
    ports:
      - ${SPEECHT5_PORT:-7055}:7055
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7055/health"]
      interval: 10s
      timeout: 6s
      retries: 18